# Basic site settings
title: "Kushal Kumar"
description: "Applied Scientist | AI/ML Research | MS CS Applicant"
url: "https://YOUR_USERNAME.github.io"
baseurl: "" # Keep blank for a user/organization site

# Theme
remote_theme: "mmistakes/minimal-mistakes"

# Author profile
author:
  name: "Kushal Kumar"
  avatar: "/assets/headshot.jpg"
  bio: "Applied Scientist @ Amazon | Research in Retrieval, Multimodal AI, Continual Learning"
  location: "Seattle, WA"
  links:
    - label: "Resume"
      icon: "fas fa-file-alt"
      url: "/assets/resume.pdf"
    - label: "Google Scholar"
      icon: "ai ai-google-scholar"
      url: "https://scholar.google.com/"
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/YOUR_USERNAME"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://linkedin.com/in/YOUR_LINKEDIN"
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:kushal@example.com"

# Plugins (must be whitelisted by GitHub Pages)
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag

# Navigation
header_pages:
  - index.md
  - about.md
  - publications.md
  - projects.md
  - cv.md

# Theme settings
minimal_mistakes_skin: "default" # other skins: air, contrast, dark, neon
markdown: kramdown
highlighter: rouge

# Collections
collections:
  posts:
    output: true

# Defaults
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
