# Basic site settings
title: ""
url: "https://kushlku.github.io"

# Theme
remote_theme: "mmistakes/minimal-mistakes"

# Author profile
author:
  name: "Kushal Kumar"
  avatar: "/assets/headshot.jpg"
  bio: "Applied Scientist II @ Amazon"
  location: "New York, NY"
  links:
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/kushal-kumar-1a8554118/"
    - label: "Google Scholar"
      icon: "fas fa-graduation-cap"
      url: "https://scholar.google.com/citations?user=DQwPDxIAAAAJ&hl=en"
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/kushlku"
    - label: "Resume"
      icon: "fas fa-file-alt"
      url: "/assets/resume.pdf"
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:kushlku@amazon.com"

# Plugins (must be whitelisted by GitHub Pages)
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-include-cache

navbar:
  - title: "About"
    url: "#about"
  - title: "Projects"
    url: "#projects"
  - title: "Publications"
    url: "#publications"
  - title: "Education"
    url: "#education.md"
  - title: "Hobbies"
    url: "#hobbies"

# Theme settings
minimal_mistakes_skin: "default" # other skins: default, air, contrast, dark, neon
theme_mode: "light"   # force light mode, ignore user preference
markdown: kramdown
highlighter: rouge

# Collections
collections:
  posts:
    output: true

# Defaults
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
