# Basic site settings
title: "Kushal Kumar"
description: "Applied Scientist II"
url: "https://kushlku.github.io"

# Theme
remote_theme: "mmistakes/minimal-mistakes"

# Author profile
author:
  name: "Kushal Kumar"
  avatar: "/assets/headshot.jpg"
  bio: "Applied Scientist @ Amazon | Research in Retrieval, Multimodal AI, Continual Learning"
  location: "New York, NY"
  links:
    - label: "Resume"
      icon: "fas fa-file-alt"
      url: "/assets/resume.pdf"
    - label: "Google Scholar"
      icon: "google-scholar"
      url: "https://scholar.google.com/citations?user=DQwPDxIAAAAJ&hl=en"
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/kushlku"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/kushal-kumar-1a8554118/"
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:kushal@amazon.com"

# Plugins (must be whitelisted by GitHub Pages)
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-include-cache

# Navigation
header_pages:
  - index.md
  - about.md
  - publications.md
  - projects.md
  - cv.md

# Theme settings
minimal_mistakes_skin: "default" # other skins: air, contrast, dark, neon
markdown: kramdown
highlighter: rouge

# Collections
collections:
  posts:
    output: true

# Defaults
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
